language: node_js
cache:
  - yarn
node_js:
  - '12'
  - '11'
script:
  - yarn test:coveralls
services: 
  - mongodb
env:
  global:
    - NODE_ENV=test
    - APP_NAME=restbest
    - APP_VERSION=1.0
    - JWT_SECRET=changechangechangeit
    - MASTER_KEY=yourSecretMasterKey
    - MONGODB_URI=mongodb://localhost:27017/restbest
notifications:
  email: false